# Change prefix from Ctrl+b to Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g status-keys vi
set -g mode-keys vi

# Looks

set -g status-style bg=default,fg=white

setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=green bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

set -g status-right ''
